name: left_pad
description: a really powerful api to add padding to strings
version: 1.0.0
homepage: https://github.com/chrisdlangham/left_pad

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
